spring:
  application:
    name: terrible-directory-scanner

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  cloud:
    stream:
      bindings:
        directoryChannel:
          destination: terrible-directory-scanner
